version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - python-backend

  # Python Backend Service
  # 這是自定義的服務名稱,可以根據需求自行命名
  # 此名稱用於在 Docker Compose 網絡中識別和引用此服務
  # 其他服務可以使用 "python-backend" 作為主機名來連接此服務
  python-backend:
    build: ./python-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # 使用services level宣告的volume
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: # 這邊宣告 volume
